# Generated by Django 4.1.4 on 2022-12-21 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('created_date', models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_testimony', models.CharField(max_length=300)),
                ('student_course', models.CharField(max_length=150)),
            ],
        ),
    ]
