# Generated by Django 4.1.4 on 2022-12-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccesStorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='success_stories_images')),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('course_completed_description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.DeleteModel(
            name='SuccesStories',
        ),
    ]
