# Generated by Django 4.1.4 on 2022-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonieIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('paragraph', models.CharField(max_length=300)),
            ],
        ),
    ]
