# Generated by Django 4.1.4 on 2022-12-13 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_successtorie_rename_courses_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='background_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='background_images'),
            preserve_default=False,
        ),
    ]
