# Generated by Django 4.1.4 on 2022-12-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_course', models.CharField(max_length=200)),
                ('available_course_span', models.CharField(max_length=100)),
                ('course_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailableInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_skilled_instructor', models.CharField(max_length=150)),
                ('available_skilled_instructor_span', models.CharField(max_length=150)),
                ('skilled_instructors_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_subject', models.CharField(max_length=100)),
                ('available_subject_span', models.CharField(max_length=100)),
                ('subject_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HappyStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_student', models.CharField(max_length=200)),
                ('happy_student_span', models.CharField(max_length=200)),
                ('number_of_happy_student', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='available_course',
        ),
        migrations.RemoveField(
            model_name='about',
            name='available_course_span',
        ),
        migrations.RemoveField(
            model_name='about',
            name='available_skilled_instructor',
        ),
        migrations.RemoveField(
            model_name='about',
            name='available_skilled_instructor_span',
        ),
        migrations.RemoveField(
            model_name='about',
            name='available_subject',
        ),
        migrations.RemoveField(
            model_name='about',
            name='available_subject_span',
        ),
        migrations.RemoveField(
            model_name='about',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_student',
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_student_span',
        ),
        migrations.RemoveField(
            model_name='about',
            name='number_of_happy_student',
        ),
        migrations.RemoveField(
            model_name='about',
            name='skilled_instructors_number',
        ),
        migrations.RemoveField(
            model_name='about',
            name='subject_number',
        ),
    ]
