# Generated by Django 4.1.4 on 2022-12-15 11:18

import django.core.validators
from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_home_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
            preserve_default=False,
        ),
    ]
