# Generated by Django 4.1.4 on 2022-12-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_about_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
