# Generated by Django 4.1.4 on 2023-01-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_certficate_feature_instructor_onlineclasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='course_images')),
                ('rating', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
