# Generated by Django 4.1.4 on 2023-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='team')),
                ('twiter', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
            ],
        ),
    ]
