# Generated by Django 4.1.4 on 2022-12-15 11:42

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_about_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
