# Generated by Django 4.1.4 on 2022-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coursedescription_remove_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccesDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('breakdescription', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='successtorie',
            name='description',
        ),
    ]
