# Generated by Django 4.1.4 on 2022-12-16 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_succesdescription_remove_successtorie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('created_date', models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Date created')),
            ],
        ),
    ]
