# Generated by Django 4.1.4 on 2022-12-17 19:38

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_subscribedusers_subscribeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.CharField(max_length=500)),
                ('created_date', models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Date created')),
            ],
        ),
    ]
