# Generated by Django 4.1.4 on 2022-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactssaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactssaved',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
