# Generated by Django 4.1.4 on 2022-12-17 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_contactssaved_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactssaved',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
