# Generated by Django 4.1.4 on 2022-12-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_contactssaved_message'),
    ]

    operations = [
    ]
