# Generated by Django 4.1.4 on 2022-12-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221218_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactssaved',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
